<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuppliersTableSeeder extends Seeder
{
    public function run(): void
    {
        $companyId = DB::table('companies')->value('id');

        DB::table('suppliers')->insert([
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP001',
                'name'            => 'Chip Mong Trading Co., Ltd.',
                'phone'           => '023 883 359',
                'email'           => 'sales@chipmong.com',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោក ចាន់ ដារ៉ា',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 5000000,
                'credit_days'     => 30,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP002',
                'name'            => 'SCG Cambodia Co., Ltd.',
                'phone'           => '023 220 222',
                'email'           => 'info@scg.com.kh',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោក ស្រ៊ី ម៉ាណែ',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 8000000,
                'credit_days'     => 30,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP003',
                'name'            => 'INSEE Cement Cambodia',
                'phone'           => '023 555 666',
                'email'           => 'info@insee.com.kh',
                'address'         => 'ខេត្តកំពង់ស្ពឺ, កម្ពុជា',
                'contact_person'  => 'លោក ហេង ស្រ៊ីណា',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 6000000,
                'credit_days'     => 45,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP004',
                'name'            => 'Nippon Paint Cambodia',
                'phone'           => '023 999 111',
                'email'           => 'info@nipponpaint.com.kh',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោកស្រី ចន្ទ ​​បូ',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 3000000,
                'credit_days'     => 30,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP005',
                'name'            => 'Posco Steel Cambodia',
                'phone'           => '023 777 888',
                'email'           => 'info@posco.com.kh',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោក វង្ស ចន្ទ',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 10000000,
                'credit_days'     => 60,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP006',
                'name'            => 'PPR Pipe Import Co.',
                'phone'           => '011 222 333',
                'email'           => 'info@pprpipe.com.kh',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោក ដែន ​ស្រស់',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 2000000,
                'credit_days'     => 30,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP007',
                'name'            => 'Bosch Cambodia Distributor',
                'phone'           => '012 888 999',
                'email'           => 'sales@bosch.com.kh',
                'address'         => 'ភ្នំពេញ, កម្ពុជា',
                'contact_person'  => 'លោក ទ្រី ​រតន',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 4000000,
                'credit_days'     => 30,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'company_id'      => $companyId,
                'supplier_code'   => 'SUP008',
                'name'            => 'Kampot Cement Co., Ltd.',
                'phone'           => '033 210 300',
                'email'           => 'info@kampotcement.com',
                'address'         => 'ខេត្តកំពត, កម្ពុជា',
                'contact_person'  => 'លោក ហ៊ុន ​ម៉ាលីន',
                'opening_balance' => 0,
                'current_balance' => 0,
                'credit_limit'    => 5000000,
                'credit_days'     => 45,
                'is_active'       => true,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ]);
    }
}
